#!/usr/bin/env bash
# CP2K backend for lamaGOET's periodic branch.
#
# This file is intended to be sourced by instalation_July19/RUN_lamaGOET_release.sh.
# It deliberately
# does not change shell options globally because lamaGOET is a large sourced
# workflow. The backend fails loudly on incomplete CP2K/Tonto data.

_cp2k_tonto_error() {
    echo "lamaGOET/CP2K: ERROR: $*" >&2
    return 1
}

_cp2k_tonto_require_file() {
    [ -f "$1" ] || _cp2k_tonto_error "required file not found: $1"
}

_cp2k_tonto_require_command() {
    command -v "$1" >/dev/null 2>&1 || _cp2k_tonto_error "required command not found: $1"
}

_cp2k_tonto_abspath() {
    python3 - "$1" <<'PY'
from pathlib import Path
import sys
print(Path(sys.argv[1]).expanduser().resolve())
PY
}

_cp2k_tonto_functional() {
    if [ -n "${CP2K_XC_FUNCTIONAL:-}" ]; then
        case "${CP2K_XC_FUNCTIONAL^^}" in
            B3LYP|PBE0|HSE*|*HYB*)
                _cp2k_tonto_error \
                    "hybrid functional '$CP2K_XC_FUNCTIONAL' needs an explicit CP2K &HF setup; use a custom template"
                return 1
                ;;
        esac
        printf '%s\n' "$CP2K_XC_FUNCTIONAL"
        return 0
    fi
    case "${METHOD,,}" in
        rks|uks|blyp|ublyp) printf '%s\n' BLYP ;;
        pbe|upbe)           printf '%s\n' PBE ;;
        b3lyp|ub3lyp|pbe0|upbe0)
            _cp2k_tonto_error \
                "hybrid methods require a custom CP2K template containing the periodic &HF setup"
            return 1
            ;;
        rhf|uhf|hf)
            _cp2k_tonto_error \
                "Hartree-Fock requires a custom CP2K template containing the periodic &HF setup"
            return 1
            ;;
        *)
            _cp2k_tonto_error \
                "cannot map METHOD='${METHOD:-}' to CP2K; set CP2K_XC_FUNCTIONAL explicitly"
            return 1
            ;;
    esac
}

_cp2k_tonto_geometry_cif() {
    local candidate
    # Tonto's *.cartesian.cif2 is a grown molecular cluster and must not be
    # reused as a periodic CP2K unit cell.  The archive CIF contains the refined
    # crystallographic asymmetric unit and symmetry operations.
    for candidate in \
        "${J}.tonto_cycle.${JOBNAME}/${J}.${JOBNAME}.archive.cif" \
        "${JOBNAME}.archive.cif" \
        "${CIF}"; do
        if [ -n "$candidate" ] && [ -f "$candidate" ]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    _cp2k_tonto_error "no CIF containing the current refined cell/geometry was found"
}

_cp2k_tonto_render_input() {
    local template=$1 output=$2
    python3 - "$template" "$output" <<'PY'
from pathlib import Path
import os
import sys

template = Path(sys.argv[1]).read_text(encoding="utf-8")
replacements = {
    "__PROJECT__": os.environ["CP2K_RENDER_PROJECT"],
    "__BASIS_SET_FILE__": os.environ["CP2K_RENDER_BASIS_SET_FILE"],
    "__CHARGE__": os.environ["CP2K_RENDER_CHARGE"],
    "__MULTIPLICITY__": os.environ["CP2K_RENDER_MULTIPLICITY"],
    "__UKS_LINE__": os.environ["CP2K_RENDER_UKS_LINE"],
    "__EPS_DEFAULT__": os.environ["CP2K_RENDER_EPS_DEFAULT"],
    "__CUTOFF__": os.environ["CP2K_RENDER_CUTOFF"],
    "__REL_CUTOFF__": os.environ["CP2K_RENDER_REL_CUTOFF"],
    "__KPOINT_GRID__": os.environ["CP2K_RENDER_KPOINT_GRID"],
    "__MAX_SCF__": os.environ["CP2K_RENDER_MAX_SCF"],
    "__EPS_SCF__": os.environ["CP2K_RENDER_EPS_SCF"],
    "__SCF_GUESS__": os.environ["CP2K_RENDER_SCF_GUESS"],
    "__ADDED_MOS__": os.environ["CP2K_RENDER_ADDED_MOS"],
    "__XC_FUNCTIONAL__": os.environ["CP2K_RENDER_XC_FUNCTIONAL"],
    "__SUBSYS_INCLUDE__": os.environ["CP2K_RENDER_SUBSYS_INCLUDE"],
}
for token, value in replacements.items():
    template = template.replace(token, value)
leftovers = sorted({word for word in template.split() if word.startswith("__") and word.endswith("__")})
if leftovers:
    raise SystemExit("unreplaced CP2K template tokens: " + ", ".join(leftovers))
Path(sys.argv[2]).write_text(template, encoding="utf-8")
PY
}


# Reject lamaGOET modes that transform the crystallographic cell into a molecular
# cluster or require outputs not yet generated by the periodic CP2K prototype.
CP2K_VALIDATE_LAMAGOET_MODE() {
    local name value
    for name in POWDER_HAR SCCHARGES COMPLETESTRUCT EXPLICITMOL DEFRAGNETW XCWONLY PLOT_TONTO XWR; do
        eval "value=\${$name:-false}"
        if [[ "${value,,}" == "true" ]]; then
            _cp2k_tonto_error "$name=true is not supported by the periodic CP2K backend"
            return 1
        fi
    done
    return 0
}

# Run one periodic CP2K calculation and convert its density for Tonto.
# Uses/updates the lamaGOET globals I, J, JOBNAME, METHOD, NUMPROC, SCFCALC_BIN
# and the CP2K_PERIODIC_* variables consumed below.  The periodic cell charge
# and multiplicity are configured independently from lamaGOET's molecular
# cluster values via CP2K_CELL_CHARGE and CP2K_CELL_MULTIPLICITY.
TONTO_TO_CP2K() {
    local cp2k_bin bridge cif_converter template basis_file basis_label functional
    local geometry cycle_dir previous_dir subsys input output scf_guess uks_line
    local kp_file mokp_file basis_args=() basis_mapping

    _cp2k_tonto_require_command python3 || return 1

    cp2k_bin=${CP2K_BIN:-${SCFCALC_BIN:-}}
    [ -n "$cp2k_bin" ] || {
        _cp2k_tonto_error "set CP2K_BIN or SCFCALC_BIN to a CP2K executable"
        return 1
    }
    if [[ "$cp2k_bin" == */* ]]; then
        _cp2k_tonto_require_file "$cp2k_bin" || return 1
        cp2k_bin=$(_cp2k_tonto_abspath "$cp2k_bin") || return 1
    else
        _cp2k_tonto_require_command "$cp2k_bin" || return 1
        cp2k_bin=$(command -v "$cp2k_bin")
    fi

    local support_dir=${LAMAGOET_SCRIPT_DIR:-.}
    bridge=${CP2K_TONTO_BRIDGE:-$support_dir/cp2k_tonto_bridge.py}
    cif_converter=${CP2K_CIF_TO_SUBSYS:-$support_dir/cif_to_cp2k.py}
    template=${CP2K_TEMPLATE:-$support_dir/cp2k_periodic_har.inp.template}
    basis_file=${CP2K_BASIS_SET_FILE:-}
    basis_label=${CP2K_BASIS_SET:-${BASISSETG:-}}

    _cp2k_tonto_require_file "$bridge" || return 1
    _cp2k_tonto_require_file "$cif_converter" || return 1
    _cp2k_tonto_require_file "$template" || return 1
    [ -n "$basis_file" ] || {
        _cp2k_tonto_error "CP2K_BASIS_SET_FILE must name an all-electron CP2K basis file"
        return 1
    }
    _cp2k_tonto_require_file "$basis_file" || return 1
    [ -n "$basis_label" ] || {
        _cp2k_tonto_error "CP2K_BASIS_SET (or BASISSETG) must name an all-electron CP2K basis"
        return 1
    }

    bridge=$(_cp2k_tonto_abspath "$bridge") || return 1
    cif_converter=$(_cp2k_tonto_abspath "$cif_converter") || return 1
    template=$(_cp2k_tonto_abspath "$template") || return 1
    basis_file=$(_cp2k_tonto_abspath "$basis_file") || return 1
    geometry=$(_cp2k_tonto_geometry_cif) || return 1
    geometry=$(_cp2k_tonto_abspath "$geometry") || return 1
    functional=$(_cp2k_tonto_functional) || return 1

    I=$((I + 1))
    cycle_dir="${I}.CP2K.cycle.${JOBNAME}"
    mkdir -p "$cycle_dir" || return 1
    cycle_dir=$(_cp2k_tonto_abspath "$cycle_dir") || return 1
    subsys="$cycle_dir/${I}.${JOBNAME}.subsys.inc"
    input="$cycle_dir/${I}.${JOBNAME}.cp2k.inp"
    output="$cycle_dir/${I}.${JOBNAME}.cp2k.out"

    for basis_mapping in ${CP2K_BASIS_MAP:-}; do
        basis_args+=(--basis-map "$basis_mapping")
    done
    python3 "$cif_converter" \
        --cif "$geometry" \
        --output "$subsys" \
        --basis "$basis_label" \
        --potential ALL \
        "${basis_args[@]}" || return 1

    scf_guess=ATOMIC
    if [ "$I" -gt 1 ]; then
        previous_dir="$((I - 1)).CP2K.cycle.${JOBNAME}"
        if [ -f "$previous_dir/${JOBNAME}-RESTART.wfn" ]; then
            cp "$previous_dir/${JOBNAME}-RESTART.wfn" "$cycle_dir/${JOBNAME}-RESTART.wfn" || return 1
            scf_guess=RESTART
        fi
    fi

    uks_line=""
    if [ "${CP2K_CELL_MULTIPLICITY:-1}" -gt 1 ] || [[ "${METHOD,,}" == u* ]]; then
        uks_line="UKS T"
    fi

    export CP2K_RENDER_PROJECT="$JOBNAME"
    export CP2K_RENDER_BASIS_SET_FILE="$basis_file"
    export CP2K_RENDER_CHARGE="${CP2K_CELL_CHARGE:-0}"
    export CP2K_RENDER_MULTIPLICITY="${CP2K_CELL_MULTIPLICITY:-1}"
    export CP2K_RENDER_UKS_LINE="$uks_line"
    export CP2K_RENDER_EPS_DEFAULT="${CP2K_EPS_DEFAULT:-1.0E-12}"
    export CP2K_RENDER_CUTOFF="${CP2K_CUTOFF:-1200}"
    export CP2K_RENDER_REL_CUTOFF="${CP2K_REL_CUTOFF:-80}"
    export CP2K_RENDER_KPOINT_GRID="${CP2K_KPOINT_GRID:-2 2 2}"
    export CP2K_RENDER_MAX_SCF="${CP2K_MAX_SCF:-100}"
    export CP2K_RENDER_EPS_SCF="${CP2K_EPS_SCF:-1.0E-8}"
    export CP2K_RENDER_SCF_GUESS="$scf_guess"
    export CP2K_RENDER_ADDED_MOS="${CP2K_ADDED_MOS:-20}"
    export CP2K_RENDER_XC_FUNCTIONAL="$functional"
    export CP2K_RENDER_SUBSYS_INCLUDE="$subsys"
    _cp2k_tonto_render_input "$template" "$input" || return 1

    echo "Running CP2K, cycle number $I"
    if [ -n "${CP2K_RUN_COMMAND:-}" ]; then
        (
            cd "$cycle_dir" || exit 1
            CP2K_INPUT=$(basename "$input") \
            CP2K_OUTPUT=$(basename "$output") \
            CP2K_EXECUTABLE="$cp2k_bin" \
            bash -lc "$CP2K_RUN_COMMAND"
        ) || return 1
    elif [ "${NUMPROC:-1}" -gt 1 ]; then
        _cp2k_tonto_require_command mpirun || return 1
        (
            cd "$cycle_dir" || exit 1
            mpirun -n "$NUMPROC" "$cp2k_bin" \
                -i "$(basename "$input")" -o "$(basename "$output")"
        ) || return 1
    else
        (
            cd "$cycle_dir" || exit 1
            "$cp2k_bin" -i "$(basename "$input")" -o "$(basename "$output")"
        ) || return 1
    fi

    if ! grep -q 'PROGRAM ENDED AT' "$output"; then
        _cp2k_tonto_error "CP2K did not terminate normally; inspect $output"
        return 1
    fi

    kp_file=$(find "$cycle_dir" -maxdepth 1 -type f -name '*RESTART*.kp' -print | sort | tail -1)
    mokp_file=$(find "$cycle_dir" -maxdepth 1 -type f -name '*.mokp' -print | sort | tail -1)
    [ -n "$kp_file" ] || {
        _cp2k_tonto_error "CP2K did not produce a *RESTART*.kp density restart"
        return 1
    }
    [ -n "$mokp_file" ] || {
        _cp2k_tonto_error "CP2K did not produce MO_KP .mokp metadata (CP2K 2026.2+ required)"
        return 1
    }

    CP2K_PERIODIC_XML="$cycle_dir/${I}.${JOBNAME}.cp2k.xml"
    CP2K_TONTO_BASIS_DIR="$cycle_dir"
    CP2K_TONTO_BASIS_NAME="${CP2K_TONTO_BASIS_NAME:-cp2k-generated}"
    CP2K_TONTO_BASIS_FILE="$cycle_dir/$CP2K_TONTO_BASIS_NAME"
    CP2K_PERIODIC_MANIFEST="$cycle_dir/${I}.${JOBNAME}.cp2k-tonto.json"
    CP2K_LAST_OUTPUT="$output"

    python3 "$bridge" \
        --kp "$kp_file" \
        --mokp "$mokp_file" \
        --xml "$CP2K_PERIODIC_XML" \
        --basis "$CP2K_TONTO_BASIS_FILE" \
        --basis-name "$CP2K_TONTO_BASIS_NAME" \
        --manifest "$CP2K_PERIODIC_MANIFEST" || return 1

    CP2K_LAST_ENERGY=$(awk '/ENERGY\| Total FORCE_EVAL/{value=$NF} END{print value}' "$output")
    CP2K_LAST_RMSD=$(awk '/RMS.*density|RMS.*Density/{value=$NF} END{print value}' "$output")
    [ -n "$CP2K_LAST_ENERGY" ] || {
        _cp2k_tonto_error "could not extract the final CP2K FORCE_EVAL energy from $output"
        return 1
    }

    export CP2K_PERIODIC_XML CP2K_TONTO_BASIS_DIR CP2K_TONTO_BASIS_NAME
    export CP2K_TONTO_BASIS_FILE CP2K_PERIODIC_MANIFEST CP2K_LAST_OUTPUT
    export CP2K_LAST_ENERGY CP2K_LAST_RMSD I
    echo "CP2K cycle $I complete: E = $CP2K_LAST_ENERGY Ha"
}

# Append the generated basis and periodic density to the Tonto stdin currently
# being assembled by SCF_TO_TONTO.
CP2K_TONTO_PERIODIC_SETUP() {
    [ -n "${CP2K_PERIODIC_XML:-}" ] || {
        _cp2k_tonto_error "CP2K_PERIODIC_XML is unset; run TONTO_TO_CP2K first"
        return 1
    }
    _cp2k_tonto_require_file "$CP2K_PERIODIC_XML" || return 1
    _cp2k_tonto_require_file "$CP2K_TONTO_BASIS_FILE" || return 1

    {
        echo "   ! Periodic all-electron density generated by CP2K"
        echo "   basis_directory= $CP2K_TONTO_BASIS_DIR"
        echo "   basis_name= $CP2K_TONTO_BASIS_NAME"
        echo "   cp2k_periodic_file_name= $CP2K_PERIODIC_XML"
        echo "   process_cif_and_cp2k_data"
        echo ""
    } >> stdin
}

# Keep the lamaGOET energy variables compatible with CHECK_ENERGY/reporting.
CP2K_CHECK_ENERGY() {
    local previous
    [ -n "${CP2K_LAST_ENERGY:-}" ] || {
        _cp2k_tonto_error "CP2K_LAST_ENERGY is unset"
        return 1
    }
    if [ -z "${ENERGIA:-}" ]; then
        ENERGIA=$CP2K_LAST_ENERGY
        RMSD=${CP2K_LAST_RMSD:-0.0}
        ENERGIA2=$ENERGIA
        RMSD2=$RMSD
        DE=0.0
    else
        previous=${ENERGIA2:-$ENERGIA}
        ENERGIA2=$CP2K_LAST_ENERGY
        RMSD2=${CP2K_LAST_RMSD:-0.0}
        DE=$(python3 - "$ENERGIA2" "$previous" <<'PY'
import sys
print(float(sys.argv[1]) - float(sys.argv[2]))
PY
        ) || return 1
    fi
    export ENERGIA ENERGIA2 RMSD RMSD2 DE
    echo "CP2K energy: $ENERGIA2 Ha; delta = $DE Ha" | tee -a "${JOBNAME}.lst"
}
